### ISSUE TITLE
Icon resources

### ISSUE THREAD

**Issue by emvigo** [FairCoinTeam/fair-coin#11]
Hi,
I've just packaged the client for Arch Linux on the AUR (https://aur.archlinux.org/packages/fair-coin/) and I've been forced to do a quite ugly hack to get the icons to be installed correctly into the filesystem, namely I had to extract and convert them from the Windows ICO file using ImageMagick, which makes the latter a build dependency of the fair-coin package.
Could you provide the PNG icons (or even better a "universal" SVG icon) directly on the source tarball? This would allow me to strike out ImageMagick from the build dependencies. I hope this isn't a problematic change for your deployment scheme. 
Thanks for your great work!

**Comment by thokon00** [comment]
First off, thanks for your effort to create a binary package for Arch Linux!

At these locations you'll find icon files with various resolutions and in different formats:
 src/qt/res/images
 src/qt/res/icons

**Comment by emvigo** [comment]
Sorry if I wasn't clear enough. I was specifically referring to the application icons that desktop environments look for under /usr/share/icons/ to show them, e.g. in the application menu (KDE, XFCE, etc.) or GNOME Shell's Overview or other places (shortcuts, etc.). There are two standard ways to do this, either by providing a vector image (SVG is supported for sure; I don't know about other formats) that must be installed under /usr/share/icons/scalable, such that the DE resizes it as needed, or by providing a PNG file that is installed under /usr/share/icons/hicolor/<res>, where <res> stands for the resolution.
The best would be to provide these PNGs already at upstream. The same method that I'm using for extracting them to create the package can be used to extract them out of the Windows ICO file (ICO is a container file that usually consists of PNGs, as in your case) and include them into the main tree. Later today I'll try to fork this repository and make a pull request.
