### ISSUE TITLE
Installing in Ubuntu 14.04 failed

### ISSUE THREAD

**Issue by lupa18** [FairCoinTeam/fair-coin#12]
I tried but when run this: 
  ```LIBS=-lrt ./configure --with-incompatible-bdb --disable-tests```

y got this:
 ``` configure: error: libdb_cxx headers missing```

also installing these the problem persist:
  ```sudo apt-get install libboost-all-dev```
  ```sudo apt-get install libqt4-core libqt4-gui libqt4-dev```

**Comment by thokon00** [comment]
You need several more packages. On Ubuntu 14.04 you need at least the following packages.

apt-get install build-essential libtool autotools-dev autoconf pkg-config libssl-dev libboost-all-dev git libdb5.3-dev libdb5.3++-dev

**Comment by lupa18** [comment]
Problems persist: 

qt/qrcodedialog.cpp:21:22: fatal error: qrencode.h: No existe el archivo o el directorio
 #include <qrencode.h>
                      ^
compilation terminated.
make[1]: *** [qt/qt_libbitcoinqt_a-qrcodedialog.o] Error 1
make[1]: se sale del directorio «/<folder>/fair-coin/src»
make: *** [all-recursive] Error 1

**Comment by lupa18** [comment]
Problems persist: 

qt/qrcodedialog.cpp:21:22: fatal error: qrencode.h: No existe el archivo o el directorio
 #include <qrencode.h>
                      ^
compilation terminated.
make[1]: *** [qt/qt_libbitcoinqt_a-qrcodedialog.o] Error 1
make[1]: se sale del directorio «/<folder>/fair-coin/src»
make: *** [all-recursive] Error 1

**Comment by thokon00** [comment]
Here is a list of packages you need to install:
`build-essential libtool autotools-dev autoconf pkg-config libssl-dev libboost-all-dev git libdb5.3-dev libdb5.3++-dev libqt4-core libqt4-gui libqt4-dev libqrencode-dev libprotobuf-dev protobuf-compiler`
