### ISSUE TITLE
Can't compile GUI

### ISSUE THREAD

**Issue by mistergibson** [FairCoinTeam/fair-coin#7]
qt/qrcodedialog.cpp:21:22: fatal error: qrencode.h: No such file or directory
 #include <qrencode.h>
                      ^
compilation terminated.
make[1]: *** [qt/qt_libbitcoinqt_a-qrcodedialog.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/root/Downloads/fair-coin/src'
make: *** [all-recursive] Error 1

**Comment by thokon00** [comment]
You need to install libqrencode development package.

If you are on ubuntu try:

sudo apt-get install libqrencode-dev

BTW, what exact configure command did you use?
