### ISSUE TITLE
electrum fair does change bitcoin electrum icon

### ISSUE THREAD

**Issue by TupambaeNet** [FairCoinTeam/fair-coin#9]
Hi there.
Didn't find issues option in the electrum fair branch.
The electrum-fair wallet changed bitcoin electrum wallet icon on a debian wheezy LXDE instalation.
![captura de pantalla de 2015-08-17 21 06 50](https://cloud.githubusercontent.com/assets/1240367/9319369/2a20a646-4524-11e5-89f2-fece9c9ab8f4.png)

**Comment by thokon00** [comment]
Thanks for letting us know. I just enabled 'issues' for the electrum-fair repo. Please re-file your report there.
